### ISSUE TITLE
v1.81.3 - TypeError: Cannot read properties of undefined (reading 'p')

### ISSUE THREAD

**Issue by joatb** [ionic-team/vscode-extension#164]
`2024-03-25 12:17:16.113 [error] Activating extension Ionic.ionic failed due to an error:
2024-03-25 12:17:16.113 [error] TypeError: Cannot read properties of undefined (reading 'p')
	at checkPrivacyManifest (/home/username/.vscode/extensions/ionic.ionic-1.81.3/out/xcode.js:50:23)
	at async checkCapacitorRules (/home/username/.vscode/extensions/ionic.ionic-1.81.3/out/rules-capacitor.js:68:9)
	at async getRecommendations (/home/username/.vscode/extensions/ionic.ionic-1.81.3/out/recommend.js:215:9)
	at async inspectProject (/home/username/.vscode/extensions/ionic.ionic-1.81.3/out/project.js:479:5)
	at async reviewProject (/home/username/.vscode/extensions/ionic.ionic-1.81.3/out/project.js:435:21)
	at async activate (/home/username/.vscode/extensions/ionic.ionic-1.81.3/out/extension.js:337:25)
	at async u.n (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:140:6255)
	at async u.m (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:140:6218)
	at async u.l (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:140:5675)`

Downgrading into version v1.80.0 is working for me.

**Comment by dtarnawsky** [comment]
Thanks for the report @joatb ,

Are you able to supply your code? If you can send it to damian@ionic.io then I can investigate.

In v1.81.5 This should now be a logged error (not a full-on crash) so it will not affect your ability to use the extension. The error is related to the searching through the iOS project to see if there needs to be privacy manifest changes.

**Comment by joatb** [comment]
Thank you very much, now in v1.81.5 it works correctly, unfortunately I don't have permission to share the code, but if you need any information I can share it with you.

**Comment by ahmadtawakol** [comment]
@dtarnawsky I've been having the same exact problem. 1.81.5 has fixed it for me, but the error is still being logged though. I currently don't have an iOS project added, so there would be nothing to search through. I am guessing this is the cause of the error for me. All my other projects that have an iOS project added work fine with no errors.

**Comment by dtarnawsky** [comment]
Hey @ahmadtawakol , If you were to remove @capacitor/ios from your project then it won't warn about that error.
In the next version of the extension - it will also not warn about the error because (I'm guessing) you dont even have an ios folder.

**Comment by ahmadtawakol** [comment]
I forgot that I had @capacitor/ios installed! Removing it has made the error go away. Thank you! And yes, I don't have an ios folder in my project.
