### ISSUE TITLE
Error: `CocoaPods requires your terminal to be using UTF-8 encoding`

### ISSUE THREAD

**Issue by robingenz** [ionic-team/vscode-extension#5]
Hey,
first of all: very cool plugin! Kudos to Damian for this great work.
I had one little problem the first time I ran `Sync`.
This was the console output:

```
npx cap sync✔ Copying web assets from www to android/app/src/main/assets/public in 438.79ms
✔ Creating capacitor.config.json in android/app/src/main/assets in 906.29μp
(node:54074) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/robingenz/Documents/GitHub/capacitor-plugin-demo/node_modules/tslib/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
✔ copy android in 451.01ms
✔ Updating Android plugins in 3.92ms
[info] Found 16 Capacitor plugins for android:
       @capacitor-community/keep-awake@2.1.1
       @capacitor-community/privacy-screen@2.1.1
       @capacitor-community/text-to-speech@1.1.2
       @capacitor/app@1.1.0
       @capacitor/camera@1.2.4
       @capacitor/filesystem@1.1.0
       @capacitor/haptics@1.1.4
       @capacitor/keyboard@1.2.1
       @robingenz/capacitor-android-dark-mode-support@1.0.1
       @robingenz/capacitor-app-update@1.3.1
       @robingenz/capacitor-background-task@1.0.1
       @robingenz/capacitor-badge@1.2.1
       @robingenz/capacitor-file-picker@0.2.3
       @robingenz/capacitor-managed-configurations@0.1.4
       @robingenz/capacitor-photo-editor@0.0.3
       @robingenz/capacitor-screen-orientation@1.1.4
✔ update android in 36.32ms
✔ Copying web assets from www to ios/App/App/public in 340.49ms
✔ Creating capacitor.config.json in ios/App/App in 340.33μp
✔ copy ios in 345.36ms
✔ Updating iOS plugins in 3.24ms
[info] Found 15 Capacitor plugins for ios:
       @capacitor-community/keep-awake@2.1.1
       @capacitor-community/privacy-screen@2.1.1
       @capacitor-community/text-to-speech@1.1.2
       @capacitor/app@1.1.0
       @capacitor/camera@1.2.4
       @capacitor/filesystem@1.1.0
       @capacitor/haptics@1.1.4
       @capacitor/keyboard@1.2.1
       @robingenz/capacitor-app-update@1.3.1
       @robingenz/capacitor-background-task@1.0.1
       @robingenz/capacitor-badge@1.2.1
       @robingenz/capacitor-file-picker@0.2.3
       @robingenz/capacitor-managed-configurations@0.1.4
       @robingenz/capacitor-photo-editor@0.0.3
       @robingenz/capacitor-screen-orientation@1.1.4
✖ Updating iOS native dependencies with pod install - failed!
✖ update ios - failed!
[error] [33mWARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
        Consider adding the following to ~/.profile:
        
        export LANG=en_US.UTF-8
        [0m
        objc[54091]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x1edee2b90) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10456c2c8). One of the two will be used. Which one is undefined.
        objc[54091]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x1edee2be0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10456c318). One of the two will be used. Which one is undefined.
        /opt/homebrew/Cellar/ruby/3.0.2_1/lib/ruby/3.0.0/unicode_normalize/normalize.rb:141:in `normalize': Unicode Normalization not appropriate for ASCII-8BIT (Encoding::CompatibilityError)
        from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:166:in `unicode_normalize'
        from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:166:in `installation_root'
        from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:226:in `podfile_path'
        from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface/error_report.rb:105:in `markdown_podfile'
        from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface/error_report.rb:30:in `report'
        from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:66:in `report_error'
        from /opt/homebrew/lib/ruby/gems/3.0.0/gems/claide-1.0.3/lib/claide/command.rb:396:in `handle_exception'
        from /opt/homebrew/lib/ruby/gems/3.0.0/gems/claide-1.0.3/lib/claide/command.rb:337:in `rescue in run'
        from /opt/homebrew/lib/ruby/gems/3.0.0/gems/claide-1.0.3/lib/claide/command.rb:324:in `run'
        from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
        from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
        from /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/bin/pod:23:in `load'
        from /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/bin/pod:23:in `<main>'
        /opt/homebrew/Cellar/ruby/3.0.2_1/lib/ruby/3.0.0/unicode_normalize/normalize.rb:141:in `normalize': Unicode Normalization not appropriate for ASCII-8BIT (Encoding::CompatibilityError)
        from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:166:in `unicode_normalize'
        from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:166:in `installation_root'
        from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:226:in `podfile_path'
        from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:205:in `podfile'
        from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:160:in `verify_podfile_exists!'
        from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/command/install.rb:46:in `run'
        from /opt/homebrew/lib/ruby/gems/3.0.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
        from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
        from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
        from /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/bin/pod:23:in `load'
        from /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/bin/pod:23:in `<main>'
```
After I added `export LANG=en_US.UTF-8` to `.zshrc` it worked. I still wonder why this was necessary, because it works fine when I enter the command manually in the VSCode terminal.

BTW: I had to restart VSCode afterwards because I kept getting the following message when I pressed `Sync` again: `The operation "Sync" is already running. Click on the operation in the status bar to cancel it.` Unfortunately I could not find a way to cancel.

**Comment by dtarnawsky** [comment]
Hi @robingenz,

Thanks for the bug report. I've fixed the issue where an error in running an operation causes "`Operation X is already running...`" error. This fix will be in the 0.0.6 release.

The error related CocoaPods is likely caused by your terminal having a different default language other than en_US (or encoding other than UTF-8) and CocoaPods not handling that scenario. To help me reproduce the error can you type `echo $LANG` in your VSCode terminal and post the output It should be something like en_US.UTF-8 (you may need to try this without your change to .zshrc).

**Comment by robingenz** [comment]
Hi @dtarnawsky, thank you!

> To help me reproduce the error can you type echo $LANG in your VSCode terminal and post the output It should be something like en_US.UTF-8 (you may need to try this without your change to .zshrc).

Sure, i reverted everything. This is my output:

```
$ echo $LANG

de_DE.UTF-8
```

**Comment by dtarnawsky** [comment]
A similar issue is documented [here](https://github.com/CocoaPods/CocoaPods/issues/9347#issuecomment-559069320) for Flutters VS Code extension. 

To attempt to get around this issue when the sync command is run in node (using child_process exec) it is now setting an environment variable for `LANG` of `en_US.UTF-8`. You can [download 0.0.7](https://vs-ionic.netlify.app/) of the extension which contains this fix. The challenge was that even after setting my Mac's language to German I wasn't able to reproduce the same error but hopefully it fixes the issue on your setup.

**Comment by robingenz** [comment]
I installed version `0.0.7` and now it works! Great work, thank you!
