### ISSUE TITLE
Bug: The "path" argument must be of type string. Received undefined.

### ISSUE THREAD

**Issue by neonish** [ionic-team/vscode-extension#56]
Hi!

I'm using version 1.9.4 of the plugin. When I click on "Debug" in the menu, no options are shown below and I receive the following error message: `The "path" argument must be of type string. Received undefined.`
![Bildschirmfoto 2022-09-06 um 09 06 58](https://user-images.githubusercontent.com/29614734/188576223-9688045d-cd25-4697-b759-4cacec3f98d9.png)

There is no log output with further information, so I can't really tell which "path" argument is meant. All string values in the plugin settings are set, so there's no undefined value. Regular "Run" on Web works fine.

Do you have any clue on what's meant here or can you help me debug this issue?

**Comment by ChrsCrss** [comment]
I found this error in "Log (Extension Host)":

```
[2022-09-06 09:35:28.902] [exthost] [error] TypeError: Cannot read properties of undefined (reading 'tip')
    at /Users/cc/.vscode/extensions/ionic.ionic-1.9.4/out/extension.js:260:24
    at c._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:63770)
    at c.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:64474)
    at i._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:95:13689)
    at i._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:95:13371)
    at i._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:95:12141)
    at i._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:95:11042)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:95:8950
    at b.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
    at p.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
    at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
    at a.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:19042)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:17079
    at b.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
    at p.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
    at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
    at a.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:19042)
    at r._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:23854)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:21224
    at b.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
    at p.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
    at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
    at v.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:15873)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:15003
    at Socket.d (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:26763)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) ionic.stop {"value":"Ionic.ionic","_lower":"ionic.ionic"}
[2022-09-06 09:37:35.028] [exthost] [warning] Invalid message item: undefined
```

**Comment by dtarnawsky** [comment]
Do you have Android Studio installed? Windows or Mac?

The reason I ask is that the debug option uses the tool ADB (Android Debug Bridge) which is installed with Android Studio. Depending on how you have customized your installation of it the extension may not be able to find it.

**Comment by ChrsCrss** [comment]
I'm on Mac OS and yes I have Android Studio installed. Is there a way to change the adb path in the extension? Or to see the exception's actual stack trace?

**Comment by dtarnawsky** [comment]
Hi @neonish , sorry I didnt see your comment until now.

I've added a feature to allow the path to adb be overridden.
In version 1.10.1 you can go to Settings -> Advanced -> Ionic: ADB Path

**Comment by ChrsCrss** [comment]
No worries! Thanks for the adaption.

I'm still getting the same message though. Are you sure "path" argument means "adb path"? Because even if adb can't be found, there still wouldn't be a type mismatch because I input a string, right?

**Comment by dtarnawsky** [comment]
Hi @neonish , can you try opening dev tools: Click Help -> Toggle Developer Tools. The exception with stack trace may be there.

Before it gets to searching for ADB it will do a few checks on your project and capacitor.config.ts file. Perhaps there is a problem its not handling in your project. Is your source code sharable? If so then emailing damian at ionic dot io with a shared zip (or link to one) will help as I can reproduce the issue.

**Comment by ChrsCrss** [comment]
Oh well, I didn't know this feature existed! Heres the full strack trace:

```
notificationsAlerts.ts:40 TypeError: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:120:11)
    at Object.join (node:path:1172:7)
    at getCapacitorConfigWebDir (vscode-file://vscode…configure.js:123:17)
    at Project.getDistFolder (vscode-file://vscode…t/project.js:352:67)
    at Recommendation.r.whenExpanded (vscode-file://vscode…/recommend.js:96:98)
    at IonicTreeProvider.getChildren (vscode-file://vscode…e-provider.js:58:32)
    at p.fetchChildrenNodes (vscode-file://vscode…rocess.js:106:19785)
    at p.getChildren (vscode-file://vscode…rocess.js:106:15966)
    at h.$getChildren (vscode-file://vscode…rocess.js:106:11998)
    at i._doInvokeHandler (vscode-file://vscode…Process.js:95:13689)
    at i._invokeHandler (vscode-file://vscode…Process.js:95:13371)
    at i._receiveRequest (vscode-file://vscode…Process.js:95:12141)
    at i._receiveOneMessage (vscode-file://vscode…Process.js:95:10843)
    at vscode-file://vscode…tProcess.js:95:8950
    at b.invoke (vscode-file://vscode…stProcess.js:61:145)
    at p.deliver (vscode-file://vscode…tProcess.js:61:2266)
    at v.fire (vscode-file://vscode…tProcess.js:61:1844)
    at a.fire (vscode-file://vscode…Process.js:69:19042)
    at vscode-file://vscode…rocess.js:111:17079
    at b.invoke (vscode-file://vscode…stProcess.js:61:145)
    at p.deliver (vscode-file://vscode…tProcess.js:61:2266)
    at v.fire (vscode-file://vscode…tProcess.js:61:1844)
    at a.fire (vscode-file://vscode…Process.js:69:19042)
    at r._receiveMessage (vscode-file://vscode…Process.js:69:23854)
    at vscode-file://vscode…Process.js:69:21224
    at b.invoke (vscode-file://vscode…stProcess.js:61:145)
    at p.deliver (vscode-file://vscode…tProcess.js:61:2266)
    at v.fire (vscode-file://vscode…tProcess.js:61:1844)
    at v.acceptChunk (vscode-file://vscode…Process.js:69:15873)
    at vscode-file://vscode…Process.js:69:15003
    at Socket.d (vscode-file://vscode…Process.js:69:26763)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

Apparently the extension is unable to find the WebDir-Folder in my Capacitor Config, so here's my `capacitor.config.ts`:

```
import { CapacitorConfig } from "@capacitor/cli";

const config: CapacitorConfig = {
	appId: "io.test.appname",
	appName: "Appname",
	webDir: "www",
	bundledWebRuntime: false,
};

export default config;
```

Unfortunately I cannot share my source code at the moment … but I've checked the`www` folder and it's indeed my output dir. Is there any way to set breakpoints in `vscode-file://vscode-app/Users/cc/.vscode/extensions/ionic.ionic-1.10.1/out/capacitor-configure.js` ?

**Comment by dtarnawsky** [comment]
Hi @neonish,

Thanks so much, that capacitor config file was enough to reproduce the issue and fix it. Looks like the extension was expecting single quotes for the webDir, so in version 1.10.2 it also handles double quotes.

Version 1.10.2 should propagate out within the next hour or so and your VS Code will auto-update. When it does the problem should disappear and you'll be able to debug again.

**Comment by ChrsCrss** [comment]
@dtarnawsky it works like a charm! Thank you very much!
