### ISSUE TITLE
Activating extension Ionic.ionic failed due to an error: command 'ionic.run' already exists

### ISSUE THREAD

**Issue by nprather** [ionic-team/vscode-extension#58]
Maybe my project/workspace has become corrupt.  The ionic extension works fine for creating a new blank project, but trying to run it on a project I've used it on before returns this error:

![image](https://user-images.githubusercontent.com/3101108/192329737-7edfc673-92e7-442f-9ee5-9b62e4c14c80.png)

[2022-09-26 12:15:09.829] [exthost] [info] ExtensionService#_doActivateExtension Ionic.ionic, startup: false, activationEvent: 'onView:ionic'
[2022-09-26 12:15:10.252] [exthost] [error] Activating extension Ionic.ionic failed due to an error:
[2022-09-26 12:15:10.252] [exthost] [error] Error: command 'ionic.run' already exists
    at c.registerCommand (c:\Users\Nathan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:62105)
    at Object.registerCommand (c:\Users\Nathan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:31185)
    at activate (c:\Users\Nathan\.vscode\extensions\ionic.ionic-1.10.1\out\extension.js:299:21)
    at Function._callActivateOptional (c:\Users\Nathan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:17649)
    at Function._callActivate (c:\Users\Nathan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:17307)
    at c:\Users\Nathan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:15118
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at E._activate (c:\Users\Nathan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:8224)
    at E._waitForDepsThenActivate (c:\Users\Nathan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:8166)
    at E._initialize (c:\Users\Nathan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:7530)

**Comment by dtarnawsky** [comment]
This does look like the VS Code space for extension is hosed up. The first thing to try is to uninstall the Ionic extension, restart VS Code, then reinstall it.

If the problem persists then I would uninstall VS Code (keeping note of extensions you have installed) and reinstall again.

**Comment by nprather** [comment]
Thanks for the update.  I ended up having todo the clean install of VS Code after turning off settings sync, then re-installed ionic extension and it's working!  
Thanks for your help,
Nathan
